targets:
  $default:
    sources:
    - lib/**
    - swagger_examples/**
    - $package$
    builders:
      swagger_dart_code_generator:
        options:
          with_base_url: true
          with_converter: true
          ignore_headers: true
          use_default_null_for_lists: false
          build_only_models: false
          use_path_for_request_names: false
          include_if_null:
            enabled: true
            value: false
          input_folder: 'lib/'
          output_folder: 'lib/generated_code/'
          enums_case_sensitive: true
          default_values_map:
            - type_name: int
              default_value: '36'
          response_override_value_map:
            - url: '/store/inventory'
              method: get
              overriden_value: 'List<dynamic>'