targets:
  $default:
    sources:
      - lib/**
      - swaggers/**
      - swaggers2/**
      - swagger_examples/**
      - $package$
    builders:
      swagger_dart_code_generator:
        options:
          with_base_url: true
          with_converter: true
          use_required_attribute_for_headers: true
          ignore_headers: false
          use_default_null_for_lists: false
          use_inheritance: false
          build_only_models: false
          use_path_for_request_names: true
          include_if_null:
            enabled: true
            value: false
          input_folder: "swaggers/"
          output_folder: "lib/generated_code/"
          enums_case_sensitive: true
          default_values_map:
            - type_name: int
              default_value: "36"
            - type_name: String
              default_value: ""
          response_override_value_map:
            - url: "/store/inventory"
              method: get
              overridden_value: "List<dynamic>"
