# https://www.dartlang.org/guides/language/analysis-options

include: package:lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: false
  exclude:
    - example/**/*.dart
    - lib/**/*.g2.dart
linter:
  rules:
    - type_annotate_public_apis
    - void_checks
    - unnecessary_new