name: SwaggerDartCodeGenerator CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.1.0
    - uses: subosito/flutter-action@v1
      name: Checkout to beta
      with:
        channel: 'beta' # or: 'dev' or 'beta'
    - name: Install dependencies
      run: flutter pub get
      # working-directory: example
    - name: Run tests
      run: flutter pub run test
    - name: Flutter analyze
      run: flutter analyze
    # - name: Test coverage
    #   run: flutter pub run test_coverage --min-coverage 70
   
      
      
