name: CI for pull request

on:
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.1.0
    - uses: subosito/flutter-action@v1
      name: Checkout to beta
      with:
        channel: 'beta' # or: 'dev' or 'beta'
    - name: Install dependencies
      run: flutter pub get
      # working-directory: example
    - name: Run tests
      run: flutter pub run test
    - name: Flutter analyze
      run: flutter analyze
    - name: Flutter test coverage
      run: flutter test --coverage
    - name: Flutter remove not needed coverage
      run: lcov --remove coverage/lcov.info 'lib/extensions/*' 'lib/models/*' 'lib/swagger_models/*' -o coverage/new_lcov.info
    - uses: codecov/codecov-action@v1.0.2
      with:
        token: ffe96e52-2ac6-46e7-879b-1fea65d896a3
        file: ./coverage/new_lcov.info
    # - name: Test coverage
    #   run: flutter pub run test_coverage --min-coverage 70
   
      
      
